services:
  go-server:
    image: golang:1.26-alpine
    container_name: go-server
    volumes: 
      - ./server:/app
    working_dir: /app
    command: go run main.go
    networks:
        - lab-net

  go-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: go-client
    networks:
        - lab-net

  network-probe:
    build: ./probe
    container_name: network-probe
    volumes:
        - ./captures:/workspace/captures
        - ./certs:/workspace/certs:ro 
    network_mode: "service:go-server"
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
    stop_grace_period: 1s

networks:
  lab-net:
    driver: bridge
