services:
  go-server-backend:
    build: ./server
    container_name: go-server-backend
    networks:
        - lab-net

  go-server:
    image: nginx:alpine
    container_name: go-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl:ro
    networks:
      - lab-net
    depends_on:
      - go-server-backend

  go-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: go-client
    networks:
        - lab-net

  network-probe:
    build: ./probe
    container_name: network-probe
    volumes:
        - ./captures:/workspace/captures
        - ./certs:/workspace/certs:ro 
    network_mode: "service:go-server-backend"
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
    stop_grace_period: 1s

networks:
  lab-net:
    driver: bridge
